#-------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#-------------------------------------------------------------


# Arguments
# 1. "X": Path to the one column time series
# 2. "weights_src": The path to weights file / arima model generated by arima training script
# 3. "destination":
# 4. "p": non-seasonal AR order
# 5. "d":
# 6. "q":
# 7. "P":
# 8. "D":
# 8. "Q":
# 10. "s":


library(Matrix)

start_time <- Sys.time()

args = commandArgs(trailingOnly=TRUE)

#print(args)
if (length(args)!= 10) {
  stop("Exactly 10 arguments need to be provided. Please check the argument list.", call.=FALSE)
}


XPath = args[1]
weightsPath = args[2]
outputPath = args[3]
p= as.numeric(args[4])
d= as.numeric(args[5])
q= as.numeric(args[6])
P= as.numeric(args[7])
D= as.numeric(args[8])
Q= as.numeric(args[9])
s= as.numeric(args[10])

#data = unlist(read.csv(file=filePath , header=FALSE, sep=","))
#weights = unlist(read.csv(file=weightsPath , header=FALSE, sep=","))

data = as.matrix(readMM(XPath))
weights = as.matrix(readMM(weightsPath))

# print(XPath)
# print(weightsPath)
# print(outputPath)
# print(p)
# print(d)
# print(q)
# print(P)
# print(D)
# print(Q)
# print(s)
# print("----------")


fixedmodel = arima(data, fixed = weights, order = c(p,d,q), seasonal = list(order = c(P, D, Q), period = s), include.mean = FALSE, transform.pars = FALSE, method = c("CSS"))
sumofsquares = fixedmodel$sigma2
print(sumofsquares)
css = 0.5 * log(sumofsquares)

end_time <- Sys.time()

sprintf("R ARIMA CSS's execution time: %f", (end_time - start_time))

print(paste("arima_css=", css, sep=""))

write.table(css, file = outputPath, sep=",", row.names=FALSE, col.names= FALSE)
